# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interfaces\setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Setup(object):
    def setupUi(self, Dialog_Setup):
        Dialog_Setup.setObjectName("Dialog_Setup")
        Dialog_Setup.resize(546, 104)
        self.welcomeLabel = QtWidgets.QLabel(Dialog_Setup)
        self.welcomeLabel.setGeometry(QtCore.QRect(0, 0, 539, 51))
        self.welcomeLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.welcomeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.btnOk = QtWidgets.QPushButton(Dialog_Setup)
        self.btnOk.setGeometry(QtCore.QRect(210, 70, 112, 23))
        self.btnOk.setObjectName("btnOk")

        self.retranslateUi(Dialog_Setup)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Setup)

    def retranslateUi(self, Dialog_Setup):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Setup.setWindowTitle(_translate("Dialog_Setup", "Dialog"))
        self.welcomeLabel.setText(_translate("Dialog_Setup", "Добро пожаловать в программу \"Дневник тренировок\", пожалуйста ответьте на вопросы из формы"))
        self.btnOk.setText(_translate("Dialog_Setup", "OK"))
