# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interfaces\startTrainingDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_start_training(object):
    def setupUi(self, Dialog_start_training):
        Dialog_start_training.setObjectName("Dialog_start_training")
        Dialog_start_training.resize(400, 300)
        font = QtGui.QFont()
        font.setPointSize(8)
        Dialog_start_training.setFont(font)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_start_training)
        self.buttonBox.setGeometry(QtCore.QRect(120, 260, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.trainingType = QtWidgets.QComboBox(Dialog_start_training)
        self.trainingType.setGeometry(QtCore.QRect(200, 10, 191, 22))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.trainingType.setFont(font)
        self.trainingType.setObjectName("trainingType")
        self.trainingType.addItem("")
        self.trainingType.addItem("")
        self.trainingType.addItem("")
        self.trainingType.addItem("")
        self.label = QtWidgets.QLabel(Dialog_start_training)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog_start_training)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 50, 391, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.layoutExerc = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.layoutExerc.setContentsMargins(0, 0, 0, 0)
        self.layoutExerc.setObjectName("layoutExerc")
        self.labelPressAppr = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPressAppr.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelPressAppr.setFont(font)
        self.labelPressAppr.setObjectName("labelPressAppr")
        self.layoutExerc.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelPressAppr)
        self.spinBoxAppr = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxAppr.setObjectName("spinBoxAppr")
        self.layoutExerc.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.spinBoxAppr)
        self.spinBoxExcer = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.spinBoxExcer.setObjectName("spinBoxExcer")
        self.layoutExerc.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBoxExcer)
        self.labelPressExcer = QtWidgets.QLabel(self.formLayoutWidget)
        self.labelPressExcer.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelPressExcer.setFont(font)
        self.labelPressExcer.setObjectName("labelPressExcer")
        self.layoutExerc.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.labelPressExcer)

        self.retranslateUi(Dialog_start_training)
        self.buttonBox.accepted.connect(Dialog_start_training.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_start_training.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_start_training)

    def retranslateUi(self, Dialog_start_training):
        _translate = QtCore.QCoreApplication.translate
        Dialog_start_training.setWindowTitle(_translate("Dialog_start_training", "Dialog"))
        self.trainingType.setItemText(0, _translate("Dialog_start_training", "Прес"))
        self.trainingType.setItemText(1, _translate("Dialog_start_training", "Приседания"))
        self.trainingType.setItemText(2, _translate("Dialog_start_training", "Подтягивания"))
        self.trainingType.setItemText(3, _translate("Dialog_start_training", "Отжимания"))
        self.label.setText(_translate("Dialog_start_training", "Выберите тренировку:"))
        self.labelPressAppr.setText(_translate("Dialog_start_training", "Укажите количество подходов:"))
        self.labelPressExcer.setText(_translate("Dialog_start_training", "Укажите количество упражнений:"))
