# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interfaces\userChangeDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_User_Change(object):
    def setupUi(self, Dialog_User_Change):
        Dialog_User_Change.setObjectName("Dialog_User_Change")
        Dialog_User_Change.resize(472, 282)
        self.btnTableChange = QtWidgets.QPushButton(Dialog_User_Change)
        self.btnTableChange.setGeometry(QtCore.QRect(330, 80, 131, 41))
        self.btnTableChange.setObjectName("btnTableChange")
        self.btnNewUser = QtWidgets.QPushButton(Dialog_User_Change)
        self.btnNewUser.setGeometry(QtCore.QRect(330, 230, 131, 41))
        self.btnNewUser.setObjectName("btnNewUser")
        self.userIdSpinBox = QtWidgets.QSpinBox(Dialog_User_Change)
        self.userIdSpinBox.setGeometry(QtCore.QRect(330, 50, 131, 22))
        self.userIdSpinBox.setMinimum(1)
        self.userIdSpinBox.setMaximum(999999999)
        self.userIdSpinBox.setObjectName("userIdSpinBox")
        self.label = QtWidgets.QLabel(Dialog_User_Change)
        self.label.setGeometry(QtCore.QRect(330, 10, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(Dialog_User_Change)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 311, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)

        self.retranslateUi(Dialog_User_Change)
        QtCore.QMetaObject.connectSlotsByName(Dialog_User_Change)

    def retranslateUi(self, Dialog_User_Change):
        _translate = QtCore.QCoreApplication.translate
        Dialog_User_Change.setWindowTitle(_translate("Dialog_User_Change", "Dialog"))
        self.btnTableChange.setText(_translate("Dialog_User_Change", "Выбрать пользователя"))
        self.btnNewUser.setText(_translate("Dialog_User_Change", "Создать нового\n"
"пользователя"))
        self.label.setText(_translate("Dialog_User_Change", "Введите ID вашего\n"
"пользователя:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog_User_Change", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog_User_Change", "Имя"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog_User_Change", "Возраст"))
