# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interfaces\userDataDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Data(object):
    def setupUi(self, Dialog_Data):
        Dialog_Data.setObjectName("Dialog_Data")
        Dialog_Data.resize(377, 425)
        self.buttonBoxDIalog = QtWidgets.QDialogButtonBox(Dialog_Data)
        self.buttonBoxDIalog.setGeometry(QtCore.QRect(210, 380, 161, 41))
        self.buttonBoxDIalog.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBoxDIalog.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBoxDIalog.setObjectName("buttonBoxDIalog")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog_Data)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 50, 361, 331))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.dataFormLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.dataFormLayout.setContentsMargins(0, 0, 0, 0)
        self.dataFormLayout.setObjectName("dataFormLayout")
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.dataFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.userNameEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userNameEdit.setObjectName("userNameEdit")
        self.dataFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userNameEdit)
        self.heightLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.heightLabel.setFont(font)
        self.heightLabel.setObjectName("heightLabel")
        self.dataFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.heightLabel)
        self.userHeightEdit = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.userHeightEdit.setMinimum(30)
        self.userHeightEdit.setMaximum(250)
        self.userHeightEdit.setProperty("value", 180)
        self.userHeightEdit.setObjectName("userHeightEdit")
        self.dataFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userHeightEdit)
        self.weightLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.weightLabel.setFont(font)
        self.weightLabel.setObjectName("weightLabel")
        self.dataFormLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.weightLabel)
        self.userWeightEdit = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.userWeightEdit.setMinimum(4)
        self.userWeightEdit.setMaximum(120)
        self.userWeightEdit.setProperty("value", 75)
        self.userWeightEdit.setObjectName("userWeightEdit")
        self.dataFormLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.userWeightEdit)
        self.ageLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.dataFormLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ageLabel)
        self.userAgeEdit = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.userAgeEdit.setMinimum(10)
        self.userAgeEdit.setMaximum(250)
        self.userAgeEdit.setProperty("value", 18)
        self.userAgeEdit.setObjectName("userAgeEdit")
        self.dataFormLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.userAgeEdit)
        self.mainLabel = QtWidgets.QLabel(Dialog_Data)
        self.mainLabel.setGeometry(QtCore.QRect(6, 9, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.mainLabel.setFont(font)
        self.mainLabel.setObjectName("mainLabel")
        self.btnChangeUser = QtWidgets.QPushButton(Dialog_Data)
        self.btnChangeUser.setGeometry(QtCore.QRect(10, 390, 171, 23))
        self.btnChangeUser.setObjectName("btnChangeUser")

        self.retranslateUi(Dialog_Data)
        self.buttonBoxDIalog.accepted.connect(Dialog_Data.accept) # type: ignore
        self.buttonBoxDIalog.rejected.connect(Dialog_Data.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Data)

    def retranslateUi(self, Dialog_Data):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Data.setWindowTitle(_translate("Dialog_Data", "Dialog"))
        self.nameLabel.setText(_translate("Dialog_Data", "Введите ваше имя:"))
        self.heightLabel.setText(_translate("Dialog_Data", "Введите ваш рост в см:"))
        self.weightLabel.setText(_translate("Dialog_Data", "Введите ваш вес в кг:"))
        self.ageLabel.setText(_translate("Dialog_Data", "Введите ваш возраст:"))
        self.mainLabel.setText(_translate("Dialog_Data", "Введите ваши данные:"))
        self.btnChangeUser.setText(_translate("Dialog_Data", "Выбрать пользователя"))
