# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interfaces\confirms\confirmDialog_userEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Confirm_User_Edit(object):
    def setupUi(self, Dialog_Confirm_User_Edit):
        Dialog_Confirm_User_Edit.setObjectName("Dialog_Confirm_User_Edit")
        Dialog_Confirm_User_Edit.resize(379, 100)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_Confirm_User_Edit)
        self.buttonBox.setGeometry(QtCore.QRect(210, 60, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayoutWidget = QtWidgets.QWidget(Dialog_Confirm_User_Edit)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 51))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.dataFormLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.dataFormLayout.setContentsMargins(0, 0, 0, 0)
        self.dataFormLayout.setObjectName("dataFormLayout")
        self.nameLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.dataFormLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.userNameEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.userNameEdit.setObjectName("userNameEdit")
        self.dataFormLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.userNameEdit)
        self.ageLabel = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ageLabel.setFont(font)
        self.ageLabel.setObjectName("ageLabel")
        self.dataFormLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.ageLabel)
        self.userAgeEdit = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.userAgeEdit.setMinimum(10)
        self.userAgeEdit.setMaximum(250)
        self.userAgeEdit.setProperty("value", 18)
        self.userAgeEdit.setObjectName("userAgeEdit")
        self.dataFormLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userAgeEdit)

        self.retranslateUi(Dialog_Confirm_User_Edit)
        self.buttonBox.accepted.connect(Dialog_Confirm_User_Edit.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_Confirm_User_Edit.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_Confirm_User_Edit)

    def retranslateUi(self, Dialog_Confirm_User_Edit):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Confirm_User_Edit.setWindowTitle(_translate("Dialog_Confirm_User_Edit", "Dialog"))
        self.nameLabel.setText(_translate("Dialog_Confirm_User_Edit", "Введите новое имя:"))
        self.ageLabel.setText(_translate("Dialog_Confirm_User_Edit", "Введите новый возраст:"))
