# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interfaces\confirmDialog_userNoneId.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_User_None_Id(object):
    def setupUi(self, Dialog_User_None_Id):
        Dialog_User_None_Id.setObjectName("Dialog_User_None_Id")
        Dialog_User_None_Id.resize(211, 88)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog_User_None_Id)
        self.buttonBox.setGeometry(QtCore.QRect(20, 50, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog_User_None_Id)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog_User_None_Id)
        self.buttonBox.accepted.connect(Dialog_User_None_Id.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog_User_None_Id.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog_User_None_Id)

    def retranslateUi(self, Dialog_User_None_Id):
        _translate = QtCore.QCoreApplication.translate
        Dialog_User_None_Id.setWindowTitle(_translate("Dialog_User_None_Id", "Dialog"))
        self.label.setText(_translate("Dialog_User_None_Id", "Ползователя с таким ID нет!"))
